"""Agregar campo qr_version a Familia

Revision ID: 4a399acf2987
Revises: a736e9a63786
Create Date: 2025-08-12 12:46:13.149876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a399acf2987'
down_revision = 'a736e9a63786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('familia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_version', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_familia_qr_token'), type_='unique')
        batch_op.drop_column('qr_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('familia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_token', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_familia_qr_token'), ['qr_token'])
        batch_op.drop_column('qr_version')

    # ### end Alembic commands ###
