"""Agregar latitud y longitud a EventoQR

Revision ID: 6701b6a400f2
Revises: 
Create Date: 2025-06-12 08:52:20.753506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6701b6a400f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_qr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_qr', schema=None) as batch_op:
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
