"""Permitir qr_filename nullable

Revision ID: a852ad981ecb
Revises: abc7e17e3df8
Create Date: 2025-06-16 14:44:25.546161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a852ad981ecb'
down_revision = 'abc7e17e3df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_qr', schema=None) as batch_op:
        batch_op.alter_column('qr_filename',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_qr', schema=None) as batch_op:
        batch_op.alter_column('qr_filename',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
