"""Agregar campos a EventoQR

Revision ID: afe438e62657
Revises: 4af5164e5b92
Create Date: 2025-06-19 12:10:07.107696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe438e62657'
down_revision = '4af5164e5b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_qr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requiere_ubic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('valid_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('valid_to', sa.DateTime(), nullable=True))

    with op.batch_alter_table('evento_qr_registro', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('movimiento_puntos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaccion', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('movimiento_puntos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('evento_qr_registro', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('evento_qr', schema=None) as batch_op:
        batch_op.drop_column('valid_to')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('requiere_ubic')

    # ### end Alembic commands ###
